services:
  - type: web
    name: student-management
    runtime: docker
    plan: starter
    buildCommand: echo "Build is handled by Dockerfile"
    startCommand: echo "Start is handled by Dockerfile"
    envVars:
      - key: APP_NAME
        value: "Student Management"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        fromService:
          type: web
          name: student-management
          property: host
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: en_US
      - key: APP_MAINTENANCE_DRIVER
        value: file
      - key: PHP_CLI_SERVER_WORKERS
        value: "4"
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: single
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: "120"
      - key: SESSION_ENCRYPT
        value: "false"
      - key: SESSION_PATH
        value: /
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: MAIL_MAILER
        value: log
      - key: VITE_APP_NAME
        value: "Student Management"
      # Optional: Set to true if you want to seed the database on first deploy
      - key: SEED_DATABASE
        value: "true"
      # Laravel will generate this automatically if not provided
      - key: APP_KEY
        generateValue: true
