services:
  - type: web
    name: student-management
    env: ubuntu
    plan: free
    buildCommand: ./render-build.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_KEY
        value:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
